---
title: "Basic Skills in Higher Education: A Cross-National Comparison
Case Study"
bibliography: refs.bib
csl: apa.csl
keywords: 
  - Basic Skills
  - Academic Offering
  - Latin American
  - Bipartite Network Modeling
abstract: |
  This case study compares the emphasis on ten basic skills as advertised in 3,155 university programs from 481 universities in nine Latin American countries. We model the emphasis on these basic skills as an undirected bipartite network where basic skills are regarded as means that facilitate learning and a rapid acquisition of knowledge. While descriptive analyses reveal that the academic offering is weakly connected to basic skills, inferential analyses based on exponential random graph estimates confirm that scientific reasoning is consistently the most central skill in Latin American graduate programs, while mathematics and writing are less important skills.
format:  # <--- Reemplaza 'format: docx: default' por esta estructura
  docx:
    output_dir: "/home/jcc/Documents/GitHub/BasicSkillsLatam/"
---

# Introduction

Basic skills such as reading comprehension, writing, speaking, and critical thinking are essential for both university students and faculty. With the widespread adoption of the so-called "Large Language Models" (LLMs), such as ChatGPT and Microsoft Copilot, there is growing consensus that these technologies have the potential to transform higher education and the way we teach and learn these and other skills [@Extance2023]. Although these technologies have only recently been introduced into classrooms, educational researchers have employed various methodological approaches to evaluate their effects on students’ skills, such as creativity [@Fisher2025] and critical thinking [@Essien2024]. Here, we introduce a cross-national comparative case study that focuses on basic skills in higher education as an additional approach that enriches the methodological toolbox of empirical educational researchers. Our approach leverages principles of network science in education [@Cramer2018]. Network science has been employed to enhance the teaching of mathematics in both undergraduate [@Porter2018] and postgraduate courses [@Gera2018]. In curriculum development, network science has served to evaluate doctoral programs in the United States of America [@Panagakou2018] and to inspire similar efforts in Europe [@Kertesz2018]. It has also provided several insights into the complex interplay between job requirements and workers’ skills [@alabdulkareem2018]. More recently, it served as the framework for a case study estimating the importance of professional skills in accredited graduate marketing programs across three continental regions [@Dakduk2025]. Building upon network science, our cross-national comparative case study evaluates the relative importance of basic skills in Latin American universities. This case study is motivated by two goals: first, to provide university leaders with data-driven insights on how to conduct empirical analyses of current academic offerings; and second, to offer empirical researchers a statistical approach that enables the estimation of skills importance without relying on survey or self-report questionnaires. From this perspective, the present work integrates the framework of network science [@Sayama2018] with the logic of case study research methods [@Yin2009].

# Network science modeling in higher education

A central objective of higher education institutions is to provide instruction in technical disciplines that equip students with competencies relevant to the contemporary job market. Understanding how these competencies align with labor market demands is increasingly important for curriculum design and policy-making. In this context, network science offers a powerful framework for modeling the relationships between jobs and skills. Two primary types of network models are commonly used by researchers: unipartite networks, which represent connections among entities of the same type (e.g., skills co-occurrence within job descriptions), and bipartite networks, which link entities of different types (e.g., professions and the skills they require). These models enable researchers to analyze structural patterns, identify skill clusters, and assess the relevance of educational offerings to workforce needs. With a unipartite model, @Borner2018 visualized the dynamic skill (mis)alignment between academic push, industry pull, and educational offerings, focusing on the emerging areas of data science and data engineering in the United States of America by collecting 132,011,926 job advertisements; 3,062,277 course syllabi; and 15,691,162 abstractcs from scientific papers between January 2010 to December 2016. @Borner2018 distinguished the skills that emerged first in job postings before appearing in publications (e.g., Facebook, Industrial Engineering, Android, Business-to-Business) from those that appeared first in publications before job postings (e.g., R programming language, design of experiments, NoSQL, MapReduce, and statistical analysis). They also identified a set of skills that had an important influence in both job postings and publications (e.g., communication, writing, problem solving, teamwork and collaboration, data analysis, project management, and presentation skills). In summary, they concluded that given the notable divergence in skill sets between academic courses and job market needs, universities may need to adapt curricula to better align with industry demands of data science and technology-related skills, which are increasingly in demand across various sectors.

@Vista2020 analyzed skills’ valuation for architecture and engineering, social sciences, and production occupations, covering 182 occupational profiles described by the occupational information network (O\*NET), which is an online database with hundreds of job definitions to help students, job seekers, and business managers to understand the world of work in the United States of America (Peterson et al., 2001; National Research Council, 2010). The results reported by Vista (2020) pinpoint that skills such as critical thinking, judgment and decision making, or complex problem solving remain highly valued regardless the centrality metric used to estimate their importance. Nonetheless, the valuation of other skills can change if they are contextually linked to particular occupations. For example, the skill of social perceptiveness had the highest “transferability value” among social scientists, whereas manual dexterity ranked high for production-related occupations. Here, transferability value refers to the importance of skills in facilitating transitions between different occupations, capturing how easily a skill can be applied or adapted from one job to another, particularly in a landscape where workers may need to shift roles frequently due to changing job markets or economic conditions.

@Gadar2018 proposed a bipartite network to analyze the educational-occupation match of 15,253 subjects who worked in 402 occupations and graduated from 398 education programs delivered by 52 institutions in Hungary. Their results showed that computer science, nursing, and engineering programs connected to occupations with a scarce source of workers. They also found five components or modules in their network, but the programs-occupation connectivity was stronger in three of these modules. The first module grouped teaching, humanity, and art programs (Germanistic studies), and half of their occupations did not require a higher education diploma, although a quarter of graduates from Germanistic studies worked in the manufacturing and IT sector due in part to their advanced knowledge of the German language. The second module showed connections between business, economics, finance, human resources, social work, nursing, and medical programs with health care, teaching, child care workers, medical technicians, and personal care jobs. The third module revealed the links between engineering, IT, physics, ecology, and earth sciences with production, manufacturing, information managers, life science, and engineering professionals.

Leveraging bipartite network modeling, @Aufiero2024 characterized the occupational information network (O\*NET) through the lenses of the economic complexity framework [@Hidalgo2009]. This characterization relied on the following three steps. First, they built a job-skill progression network, where nodes represented jobs and a link between two jobs indicates statistically significant co-occurrence of skills required to carry out those two jobs. Second, they used the fitness and complexity algorithm to define a skill-based complexity measure of jobs that positively maps into wages and in the bottom–up and broad abstract/manual and routine/non-routine job characterisations, however providing a continuous and endogenous metric to assess the complexity of each set of occupational skills. Finally, elaborating upon the relatedness and corporate coherence metrics, they introduced a measure of each job’s skill coherence that negatively maps into wages. Among their findings, they noted two distinct communities. The first community revealed a notable concentration of technical skills mainly associated with industrial production processes, and the second community had a connection with more abstract skills including business, management, and art-related competencies. They noted that cross-functional skills were those related to business and management as they serve as a crucial link between these two communities. @Aufiero2024 reported that "Management and Top Executives," "Supervisors of Repair and Protective Service Occupations," "Architects" and "Life Scientists" proved to be among the top fitness jobs. In contrast, low-fitness jobs included "Food Preparation and Serving Related Workers," "Entertainment Attendants," "Financial Clerks," "Personal Appearance, and Administrative Support workers."

Leveraging keywords-in-context functions to extract soft skills explicitly mentioned in commercial brochures of university programs, @Garciachitiva2024 proposed a bipartite network structure to estimate the centrality of 31 soft skills by sampling 230 university programs for three types of graduate studies (i.e., Specialization, Master, and Doctorate) with two quality accreditation standards offered by 49 higher education institutions in Colombia. Here, soft skills refer to abilities related to socio-emotional behavioral control in programs’ intended learning outcomes [@Scheerens2020]. From this perspective, @Garciachitiva2024 characterized the skills-programs connectivity as a non-directed bipartite network with binary entries. Among their results, they showed that skills’ centrality varied as a function of the graduate program without revealing statistically significant differences. In addition, while the most central skills tend to be those related to creativity, leadership, and analytical thinking, less central skills were those related to empathy, ethical thinking, and critical thinking. Based on these results, the authors claimed to what extent emphasizing the most visible skills might imply an imbalance in the opportunities to enhance other soft skills, such as ethical thinking in students interested in becoming entrepreneurs.

More recently, @Javadian2024 developed the "Course-Skill Atlas" as a longitudinal dataset from over three million course syllabi taught at nearly three thousand higher education institutions in the United States of America. By employing a natural language processing framework called "Syllabus2O\*NET," they processed raw syllabus texts with sentence segmentation, sentence tagging, and sentence embedding to create a vector representation of the syllabi in the ability taxonomy provided by the U.S. Department of Labor’s O\*NET taxonomy. They estimated the semantic similarity between identified learning content and detailed work activities from the O\*NET taxonomy using SBERT, and generated skill vectors for each analyzed syllabus. The resulting skill profiles were aggregated by institution, year, and academic major. Among their findings, they reported a general trend of increasing alignment between skills taught in higher education and labor market demands over time. However, some specific fields, like computer science, showed stagnant syllabi diverging from rapidly evolving labor force requirements. In their analyses, they also identified distinctive skills for each field of study, revealing that similar academic fields cluster together based on shared workplace activities, forming groups such as STEM and humanities-based majors, without providing further evidence of non-technical skills or soft skills.

Finally, @Dakduk2025 presented a case study that employed bipartite network modeling to analyze the relationship between 28 professional skills associated with the role of marketing professionals and 258 graduate programs with quality accreditation standards conferred by the Association to Advance Collegiate Schools of Business (AACSB) and offered by 222 public and private universities across three continental regions (i.e., the Americas, the Europe-Africa- Middle East region, and the Asian region). By retrieving information from brochures of Master’s in Marketing offered by AACSB-accredited universities and the profile of marketing managers defined by the O\*NET database, they analyzed a sample representing 85.58% of the worldwide academic offering in Master’s in marketing, revealing that most of the global academic offerings for Master’s in Marketing programs is in the American continent (69.77%), followed by the Europe-Africa-Middle East region (19.29%) and the Asian region (10.93%). Among their findings, they reported that while descriptive analysis for skills suggests a qualitative lack of alignment between the job demands captured by O\*NET, inferential analyses based on exponential random graph model estimates showed that skill popularity and homophily coexist with a systematic yet weak alignment to job demands for marketing managers. In particular, they found that “management of personnel resources,” “judgment and decision making,” “coordination,” “active listening,” and “management of financial resources” emerged as the most popular skills offered by the programs.
